<a href="https://colab.research.google.com/github/angomoson/pytorch/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##00_pytorch

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


In [2]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [4]:
vector.ndim

1

In [5]:
vector.shape

torch.Size([2])

In [6]:
#MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
MATRIX.ndim

2

In [8]:
MATRIX.shape

torch.Size([2, 2])

In [9]:
MATRIX[0]

tensor([7, 8])

In [10]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

##Random tensors

In [14]:
#Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8865, 0.2053, 0.8755, 0.9612],
        [0.1143, 0.7734, 0.5611, 0.8484],
        [0.4626, 0.6320, 0.9303, 0.9423]])

In [15]:
random_tensor.ndim

2

In [16]:
random_tensor.shape

torch.Size([3, 4])

In [17]:
RANDOM_TENSOR = torch.rand(1,3,3)
RANDOM_TENSOR

tensor([[[0.0552, 0.4066, 0.5727],
         [0.4323, 0.8613, 0.9225],
         [0.8707, 0.4929, 0.0431]]])

In [18]:
#Creating a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height , width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#zeros and ones

In [19]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

#Creating a range of tensors and tensors-like

In [22]:
one_to_ten = torch.arange(start=1,end = 10, step = 1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#creating tensor like

ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor datatypes

In [24]:
# Float_32_tensor

float_32_tensor = torch.tensor([3.9,6.0,9.0],
                               dtype=None
                               )

In [25]:
int_32_tensor = torch.tensor([3,6,9],
                               dtype=torch.int32
                          )

In [26]:
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

## Manipulating tensors
#Addition
#Subtraction
#Multiplication
#Division


In [27]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [28]:
tensor * 10

tensor([10, 20, 30])

In [29]:
tensor - 10

tensor([-9, -8, -7])

In [30]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [31]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [32]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

In [33]:
print(tensor * tensor)

tensor([1, 4, 9])


In [34]:
torch.matmul(tensor, tensor)

tensor(14)

In [35]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[1.2859, 0.8191],
        [0.6970, 1.0667]])

In [36]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.3825, 0.5695, 1.0727],
        [0.0455, 0.2515, 0.4633],
        [0.0493, 0.1999, 0.3694]])

In [37]:
## Transpose of matrix

In [49]:
tensor_A = torch.tensor([[1,2],[4,5],[7,8]])

tensor_B = torch.tensor([[1,2],[4,5],[7,8]])

In [50]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [52]:
tensor_B.T, tensor_B.shape

(tensor([[1, 4, 7],
         [2, 5, 8]]),
 torch.Size([3, 2]))

In [53]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[  5,  14,  23],
        [ 14,  41,  68],
        [ 23,  68, 113]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [54]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
# Finding the min

torch.min(x), x.min()

(tensor(0), tensor(0))

In [56]:
# Finding the max

torch.max(x), x.max()

(tensor(90), tensor(90))

In [57]:
# Finding the mean

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [58]:
# Find the sum

torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [59]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
# Find the position in tensor that has the minimum value with argmin()
x.argmin()

tensor(0)

In [61]:
# Find the position in the tensor that has the maximum value
x.argmax()

tensor(9)

In [62]:
x[9]

tensor(90)

## Reshaping , stacking, squeezing and usqueezing tensors

* Reshaping - reshape an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side (hstack)
* Squeeze - Removes all 1 dimensions from a tensor
* Unsqueeze - add 1 dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [63]:
# Lets create a tensor

import torch

x = torch.arange(1.0,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [64]:
# Add an extra dimension

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# Change the view

z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [66]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [67]:
# Stack tensors on top of each other

In [70]:
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [71]:
# torch.squeeze() - removes all single dimensions from the target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [72]:
x_reshaped.shape

torch.Size([1, 9])

In [76]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [78]:
# Unsqueeze - adds a single dimension to a target tensor at a specific dim

print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsquueze

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew tensor: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New tensor: torch.Size([1, 9])


In [79]:
# torch.permute - rearranges the order of the dimension of the target tensor
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the x_original tensor to rearrange the axis (or dim) order

x_permuted = x_original.permute(2, 0 , 1) # shifts axis 0->, 1->2, 2->0

print(f"Previous ahape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous ahape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [80]:
x_original

tensor([[[0.0948, 0.6645, 0.7273],
         [0.7263, 0.3866, 0.6885],
         [0.2548, 0.6557, 0.5360],
         ...,
         [0.3074, 0.4293, 0.0351],
         [0.8845, 0.6553, 0.9819],
         [0.4415, 0.5106, 0.6469]],

        [[0.3698, 0.6045, 0.6565],
         [0.7123, 0.2309, 0.4298],
         [0.2708, 0.2381, 0.8622],
         ...,
         [0.7045, 0.4862, 0.2796],
         [0.5942, 0.0233, 0.7835],
         [0.6802, 0.5359, 0.2658]],

        [[0.1529, 0.8393, 0.7865],
         [0.5876, 0.5706, 0.6485],
         [0.2225, 0.6521, 0.5552],
         ...,
         [0.5076, 0.7986, 0.1547],
         [0.5078, 0.3186, 0.9076],
         [0.0857, 0.4633, 0.9544]],

        ...,

        [[0.3133, 0.0014, 0.6179],
         [0.0045, 0.3529, 0.4087],
         [0.3163, 0.8458, 0.2983],
         ...,
         [0.9553, 0.7992, 0.4575],
         [0.4443, 0.1235, 0.8429],
         [0.0643, 0.4438, 0.6829]],

        [[0.7439, 0.4129, 0.1540],
         [0.8093, 0.4856, 0.0961],
         [0.

## Indexing ( selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [81]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [82]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [85]:
#Let's on the middle bracket (dim = 1)
x[0][2]

tensor([7, 8, 9])

In [87]:
# Indexing on the most inner bracket
x[0][2][2]

tensor(9)

In [88]:
# We can also use ":" to select "all" of the dimension
x[:, 0]

tensor([[1, 2, 3]])

In [89]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:, 1]

tensor([[2, 5, 8]])

In [90]:
# Get all the values of the 0 dim but only the 1 index value of the 1st and 2nd dim
x[:, 1, 1]

tensor([5])

In [91]:
# Get index 0 of 0 and 1 dim and all values of 2nd dim
x[0, 0, :]

tensor([1, 2, 3])

In [92]:
# index on x to return 9
x[:,2,2]

tensor([9])

In [93]:
# index on x to return 3,6,9
x[:, : , 2]

tensor([[3, 6, 9]])

## Pytorch tensors and Numpy

Numpy is a popular scientific Python numerical computing library.
And because of this, Pythorch has functionality to interact with it.
* Data in Numpy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
*Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [2]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorchreflects numpy's default datatype of float64 unless specified
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
# Change the value of array, what wwill this do to `tensor` ?

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [4]:
# Tensor to Numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [5]:
numpy_tensor.dtype

dtype('float32')

In [6]:
# Change the tensor, what happens to `numpy_tensor` ?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network leanrs:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again`

To reduce the randomness in neural networks and PyTorch comes the concept of random seed.
Essentially what seed does is "flavour" the randomness.

In [7]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3986, 0.2168, 0.9704, 0.9573],
        [0.3330, 0.0140, 0.0710, 0.5540],
        [0.5733, 0.5560, 0.5666, 0.2763]])
tensor([[0.7376, 0.7383, 0.5957, 0.5766],
        [0.5094, 0.2378, 0.7050, 0.7494],
        [0.3060, 0.6599, 0.2030, 0.0362]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [9]:
# Make random tensor but reproducible

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

* Easiest - Use Google colab
* Use my own GPU
* Use cloud computing - GCP, AWS, Azure ect.


In [1]:
!nvidia-smi

Fri Apr 12 06:22:24 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
# Check for GPU access with PyTorch

import torch
torch.cuda.is_available()


True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup devvice agnostic code : https://pytorch.org/docs/stable/notes/cuda.html#best-practices

Eg: run on GPU if available, else default to CPU

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count the number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using GPU results in faster computations.

In [5]:
# Create a tensor (default on the CPU)

tensor = torch.tensor([1,2,3], device = "cpu")

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# Move tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [7]:
# Moving tensors back to the CPU

# To fix the GPU tensor with NumPy issue, we can first set it to the CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [8]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')