<a href="https://colab.research.google.com/github/angomoson/pytorch/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##00_pytorch

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


In [2]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [4]:
vector.ndim

1

In [5]:
vector.shape

torch.Size([2])

In [6]:
#MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
MATRIX.ndim

2

In [8]:
MATRIX.shape

torch.Size([2, 2])

In [9]:
MATRIX[0]

tensor([7, 8])

In [10]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

##Random tensors

In [14]:
#Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8865, 0.2053, 0.8755, 0.9612],
        [0.1143, 0.7734, 0.5611, 0.8484],
        [0.4626, 0.6320, 0.9303, 0.9423]])

In [15]:
random_tensor.ndim

2

In [16]:
random_tensor.shape

torch.Size([3, 4])

In [17]:
RANDOM_TENSOR = torch.rand(1,3,3)
RANDOM_TENSOR

tensor([[[0.0552, 0.4066, 0.5727],
         [0.4323, 0.8613, 0.9225],
         [0.8707, 0.4929, 0.0431]]])

In [18]:
#Creating a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height , width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#zeros and ones

In [19]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

#Creating a range of tensors and tensors-like

In [22]:
one_to_ten = torch.arange(start=1,end = 10, step = 1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#creating tensor like

ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor datatypes

In [24]:
# Float_32_tensor

float_32_tensor = torch.tensor([3.9,6.0,9.0],
                               dtype=None
                               )

In [25]:
int_32_tensor = torch.tensor([3,6,9],
                               dtype=torch.int32
                          )

In [26]:
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

## Manipulating tensors
#Addition
#Subtraction
#Multiplication
#Division


In [27]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [28]:
tensor * 10

tensor([10, 20, 30])

In [29]:
tensor - 10

tensor([-9, -8, -7])

In [30]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [31]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [32]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

In [33]:
print(tensor * tensor)

tensor([1, 4, 9])


In [34]:
torch.matmul(tensor, tensor)

tensor(14)

In [35]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[1.2859, 0.8191],
        [0.6970, 1.0667]])

In [36]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.3825, 0.5695, 1.0727],
        [0.0455, 0.2515, 0.4633],
        [0.0493, 0.1999, 0.3694]])

In [37]:
## Transpose of matrix

In [49]:
tensor_A = torch.tensor([[1,2],[4,5],[7,8]])

tensor_B = torch.tensor([[1,2],[4,5],[7,8]])

In [50]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [52]:
tensor_B.T, tensor_B.shape

(tensor([[1, 4, 7],
         [2, 5, 8]]),
 torch.Size([3, 2]))

In [53]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[  5,  14,  23],
        [ 14,  41,  68],
        [ 23,  68, 113]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [54]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
# Finding the min

torch.min(x), x.min()

(tensor(0), tensor(0))

In [56]:
# Finding the max

torch.max(x), x.max()

(tensor(90), tensor(90))

In [57]:
# Finding the mean

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [58]:
# Find the sum

torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [59]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
# Find the position in tensor that has the minimum value with argmin()
x.argmin()

tensor(0)

In [61]:
# Find the position in the tensor that has the maximum value
x.argmax()

tensor(9)

In [62]:
x[9]

tensor(90)

## Reshaping , stacking, squeezing and usqueezing tensors

* Reshaping - reshape an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side (hstack)
* Squeeze - Removes all 1 dimensions from a tensor
* Unsqueeze - add 1 dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [63]:
# Lets create a tensor

import torch

x = torch.arange(1.0,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [64]:
# Add an extra dimension

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# Change the view

z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [66]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [67]:
# Stack tensors on top of each other

In [70]:
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [71]:
# torch.squeeze() - removes all single dimensions from the target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [72]:
x_reshaped.shape

torch.Size([1, 9])

In [76]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [78]:
# Unsqueeze - adds a single dimension to a target tensor at a specific dim

print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsquueze

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew tensor: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New tensor: torch.Size([1, 9])
